import "@/styles/globals.css";
import "@/styles/materialize.css";
import "@/styles/main.scss";

import { Inter } from "next/font/google";
import type { FC } from "react";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
type Props = {
  children: React.ReactNode;
};

const RootLayout: FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <title>Finance manager</title>
        <meta name="description" content="Online financial accounting" />
      </head>
      <body className={inter.className}>
        {/* <CssBaseline /> */}

        {children}
      </body>
    </html>
  );
};

export default RootLayout;
